language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip
    - virtualbox

rvm:
  - ruby

env:
  matrix:
    - SUITE=apt
    - SUITE=yum
    - SUITE=bootstrap
    - SUITE=vagrant-windows
    - SUITE=vagrant-freebsd

matrix:
  allow_failures:
    - env: SUITE=vagrant-windows
    - env: SUITE=vagrant-freebsd

sudo: true
dist: trusty

before_install:
  - curl -O https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb
  - sudo dpkg -i ./vagrant_1.9.8_x86_64.deb
  - vagrant plugin install vagrant-winrm
  - pip install -r test-requirements.txt

script:
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 6
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify $SUITE

after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
