language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - subversion
    - git
    - shellcheck
    - tree
    - python-pip

rvm:
  - ruby

env:
  - SUITE=apt
  - SUITE=yum
  - SUITE=bootstrap

sudo: true
dist: trusty

bundler_args: --without='vagrant'

install:
  - pip install -r requirements.txt
  - bundle install --without='vagrant'
  - bundle exec kitchen list

script:
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 6
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify $SUITE

after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
  - bundle exec kitchen diagnose --all
