driver:
  name: ec2
  instance_type: m3.medium
  aws_ssh_key_id: <%= ENV["USER"] %>

provisioner:
  name: salt_solo
  formula: ntp
  state_top:
    base:
      '*':
        - ntp

transport:
  name: ssh
  ssh_key: ~/.ssh/id_rsa

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: ntp
